# Práctica 0: Manipulación de datos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los conjuntos de datos que se consideran en el campo del aprendizaje automático se organizan, en general, en filas de ejemplos y columnas de atributos. [Pandas](https://pandas.pydata.org/) es un paquete de Python que proporciona estructuras de datos específicamente diseñadas para facilitar el manejo de ese tipo de conjuntos de datos. La implementación de esas estructuras se apoya en [NumPy](https://numpy.org/), que es un paquete de Python para computación científica.

Esta práctica presenta una introducción somera a ambos paquetes de Python. Para un conocimiento más completo, se emplaza al alumnado a consultar su documentación, así como bibliografía relacionada, por ejemplo:

- [Python para análisis de datos](https://fama.us.es/permalink/34CBUA_US/3enc2g/alma991013663804804987) (La [versión original en inglés](https://wesmckinney.com/book/) de este libro se encuentra disponible libremente en Internet)
- [Pandas for everyone](https://www.pearson.com/en-gb/subject-catalog/p/pandas-for-everyone-python-data-analysis/P200000007264/9780137891153) (Disponible [en línea](https://fama.us.es/permalink/34CBUA_US/3enc2g/alma991013811774604987) a través de la Biblioteca de la Universidad de Sevilla)

## Numpy

El núcleo del paquete Numpy lo conforma el objeto `ndarray`, que es una implementación del tipo de dato _array_ multidimensional (es decir, una colección de elementos identificados por uno o más índices). Las instancias de `ndarray` se diferencian de las secuencias estándar de Python fundamentalmente en que:

- Tienen un tamaño fijo.
- Se requiere que todos sus elementos sean del mismo tipo.

Estas restricciones permiten a Numpy proporcionar implementaciones eficientes de muchas operaciones matemáticas, facilitando de esta manera trabajar con grandes conjuntos de datos.

Para una mayor legibilidad del código, a la hora de importar el paquete Numpy se suele adoptar el convenio de asociarle el nombre `np`.

In [1]:
import numpy as np

### Creación de _arrays_ especificando los elementos

La función `array` permite crear _arrays_ a partir de secuencias estándar de Python anidadas.

In [2]:
a = np.array([1.2, 3.5, 5.1, 4.8, 2.3])
a

array([1.2, 3.5, 5.1, 4.8, 2.3])

In [3]:
b = np.array([(4, -3, 0, -3), (3, -5, 1, 5), (-4, 6, -10, 9)])
b

array([[  4,  -3,   0,  -3],
       [  3,  -5,   1,   5],
       [ -4,   6, -10,   9]])

**Nota**: es importante proporcionar los datos dentro de una secuencia y no como argumentos separados.

In [4]:
np.array(1.2, 3.5, 5.1)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

### Tamaño de un _array_

El tamaño de un _array_ viene determinado por su forma, que se guarda en el atributo `shape` y que es una tupla que recoge el tamaño de cada una de sus dimensiones. Cada una de estas dimensiones recibe en Numpy el nombre de eje (`axis`).

In [5]:
print(f'Número de ejes del array a: {a.ndim}')
print(f'Forma del array a: {a.shape}')
print(f'Número de elementos del array a: {a.size}')

Número de ejes del array a: 1
Forma del array a: (5,)
Número de elementos del array a: 5

In [6]:
print(f'Número de ejes del array b: {b.ndim}')
print(f'Forma del array b: {b.shape}')
print(f'Número de elementos del array b: {b.size}')

Número de ejes del array b: 2
Forma del array b: (3, 4)
Número de elementos del array b: 12

En Numpy, un vector hace referencia a un _array_ unidimensional, una matriz a un _array_ bidimensional y un tensor a un _array_ multidimensional.

El método `reshape` proporciona un _array_ con la nueva forma especificada. Hay que asegurarse de que la nueva forma es compatible con la cantidad de elementos del array. Si para un eje se especifica el valor `-1`, el tamaño de ese eje se calcula automáticamente.

In [7]:
b.reshape(4, 3)

array([[  4,  -3,   0],
       [ -3,   3,  -5],
       [  1,   5,  -4],
       [  6, -10,   9]])

In [8]:
b.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [9]:
c = b.reshape(2, 2, -1)  # Le ponemos nombre para usarlo en ejemplos posteriores
c

array([[[  4,  -3,   0],
        [ -3,   3,  -5]],

       [[  1,   5,  -4],
        [  6, -10,   9]]])

### Creación de _arrays_ especificando el tamaño

Numpy ofrece diversas funciones para crear _arrays_ con una forma determinada, pero cuyos elementos actúan como marcadores de posición que podrán cambiarse posteriormente.

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((2, 5), 3.8)  # Rellena el array con el valor especificado

array([[3.8, 3.8, 3.8, 3.8, 3.8],
       [3.8, 3.8, 3.8, 3.8, 3.8]])

In [14]:
np.empty((1, 2, 3))  # Los elementos del array son valores aleatorios que deberán modificarse convenientemente

array([[[4.92132307e-315, 0.00000000e+000, 3.15474899e+180],
        [8.78422055e+247, 0.00000000e+000, 0.00000000e+000]]])

### Tipo de dato de un _array_

El tipo de dato de los elementos de un _array_ está guardado en el atributo `dtype`.

In [15]:
print(f'Tipo de dato de los elementos del array a: {a.dtype}')
print(f'Tipo de dato de los elementos del array b: {b.dtype}')

Tipo de dato de los elementos del array a: float64
Tipo de dato de los elementos del array b: int64

Numpy tiene implementados diferentes [tipos de datos estándar](https://numpy.org/doc/stable/reference/arrays.scalars.html#built-in-scalar-types) que determinan, entre otras propiedades, la cantidad de memoria que usan.

Se puede indicar el tipo de dato de sus elementos al construir un _array_.

In [16]:
np.array([(1, 2, 3), (4, 5, 6)], dtype='float64')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
np.ones((3, 4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

La mejor manera de cambiar el tipo de dato es crear una copia del _array_ mediante el método `astype`.

In [18]:
a.astype('U')

array(['1.2', '3.5', '5.1', '4.8', '2.3'], dtype='<U32')

### Selección de elementos de un _array_

La selección de elementos de un _array_ unidimensional se puede realizar de manera análoga a las listas de Python, usando índices y rebanadas (_slices_) de la forma `i:j:k`.

**Nota**: recuérdese que en Python las secuencias se enumeran empezando con el índice 0 y que los índices negativos toman como referencia el final de la secuencia.

In [19]:
a[1]  # Selecciona el elemento de índice 1 (es decir, el segundo elemento de la secuencia)

np.float64(3.5)

In [20]:
a[-1]  # Selecciona el último elemento

np.float64(2.3)

In [21]:
a[0:2]  # El intervalo de índices definido por una rebanada es cerrado por la izquierda y abierto por la derecha

array([1.2, 3.5])

In [22]:
a[:2]  # El índice inicial por defecto es el 0

array([1.2, 3.5])

In [23]:
a[1:]  # El índice final por defecto es la longitud de la secuencia

array([3.5, 5.1, 4.8, 2.3])

In [24]:
a[::2]  # Selecciona todos los elementos de índice par

array([1.2, 5.1, 2.3])

Para los _arrays_ multidimensionales hay que especificar una expresión de selección por cada eje, separadas por comas. Para seleccionar todos los índices de un eje se usa la expresión `:` y para seleccionar todos los índices de varios ejes consecutivos se usa la expresión `...`.

In [25]:
b[:2, -2:]  # Selecciona los elementos de las dos primeras filas y dos últimas columnas

array([[ 0, -3],
       [ 1,  5]])

In [26]:
b[1, :]  # Selecciona la segunda fila como un array unidimensional

array([ 3, -5,  1,  5])

In [27]:
b[[1], :]  # Para mantener la forma del array la fila debe seleccionarse mediante una secuencia

array([[ 3, -5,  1,  5]])

In [28]:
c[0, :, :]  # Selecciona todos los elementos de índice 0 en el primer eje

array([[ 4, -3,  0],
       [-3,  3, -5]])

In [29]:
c[0, ...]  # Selecciona todos los elementos de índice 0 en el primer eje

array([[ 4, -3,  0],
       [-3,  3, -5]])

In [30]:
c[..., 0]  # Selecciona todos los elementos de índice 0 en el tercer eje

array([[ 4, -3],
       [ 1,  6]])

In [31]:
c[0]  # La selección [i] es equivalente a la selección [i, ...]

array([[ 4, -3,  0],
       [-3,  3, -5]])

También se pueden seleccionar elementos mediante secuencias de valores lógicos: se seleccionan los índices que se corresponden con el valor `True` y no se seleccionan los que se corresponden con el valor `False`. Lo habitual es usar esta manera de seleccionar proporcionando directamente una expresión que representa la condición que debe cumplirse para que un elemento sea seleccionado.

In [32]:
a[a < 4]  # Selecciona los elementos de a menores que 4

array([1.2, 3.5, 2.3])

In [33]:
b[b % 2 == 0]  # Selecciona los elementos pares de b

array([  4,   0,  -4,   6, -10])

In [34]:
d = np.array(['No', 'Sí', 'Sí', 'No', 'Sí'])
a[d == 'Sí']  # Selecciona los elementos de a indicados por d

array([3.5, 5.1, 2.3])

### Modificación de elementos de un _array_

Las expresiones de selección de elementos de un _array_ no dan como resultado un nuevo _array_, sino que proporcionan lo que se conoce como una vista del _array_ original. La combinación de estas vistas con el operador de asignación permiten modificar los elementos del _array_.

In [35]:
a[0] = 0
a

array([0. , 3.5, 5.1, 4.8, 2.3])

In [36]:
b[b % 2 == 0] += 1
b

array([[ 5, -3,  1, -3],
       [ 3, -5,  1,  5],
       [-3,  7, -9,  9]])

Las operaciones de Numpy que actúan sobre un _array_ proporcionan como resultado una vista de este si es posible, permitiendo, en ese caso, modificar el _array_ original.

In [37]:
b.reshape(4, 3)[0, 0] = 0
b

array([[ 0, -3,  1, -3],
       [ 3, -5,  1,  5],
       [-3,  7, -9,  9]])

In [38]:
b.astype('float64')[0, 0] = 5  # El método astype devuelve una copia del array original
b

array([[ 0, -3,  1, -3],
       [ 3, -5,  1,  5],
       [-3,  7, -9,  9]])

El método `copy` nos permite obtener una copia, en lugar de una vista de un _array_.

In [39]:
b.reshape(4, 3).copy()[0, 0] = 5
b

array([[ 0, -3,  1, -3],
       [ 3, -5,  1,  5],
       [-3,  7, -9,  9]])

### Funciones universales

En Numpy, las [operaciones matemáticas](https://numpy.org/doc/stable/reference/routines.math.html) están implementadas mediante _funciones universales_. Una de las propiedades de este tipo de funciones es que están vectorizadas. Esto quiere decir que al aplicarlas a un _array_, entonces se aplican a cada elemento, devolviendo los resultados en un nuevo _array_.

In [40]:
np.sqrt(a)  # Calcula la raíz cuadrada de cada elemento de a

array([0.        , 1.87082869, 2.25831796, 2.19089023, 1.51657509])

In [41]:
b + b  # Suma la matriz b consigo misma, elemento a elemento

array([[  0,  -6,   2,  -6],
       [  6, -10,   2,  10],
       [ -6,  14, -18,  18]])

Estas vectorizaciones se realizan, por supuesto, mediante bucles, pero al estar estos implementados en el lenguaje C se obtiene una mayor eficiencia que con un bucle estándar de Python.

In [42]:
%%time

[2 * x for x in range(100000)];  # El punto y coma final evita que se muestre el resultado de la expresión

CPU times: user 3.81 ms, sys: 986 μs, total: 4.79 ms
Wall time: 4.74 ms

In [43]:
%%time

2 * np.arange(100000);  # La función arange de Numpy es el equivalente de la función range de Python

CPU times: user 801 μs, sys: 71 μs, total: 872 μs
Wall time: 534 μs

Muchas operaciones escalares están implementadas como métodos del objeto _array_ y, además, pueden aplicarse a lo largo de uno o más ejes.

In [44]:
b.sum()  # Suma de todos los elementos de b

np.int64(3)

In [45]:
b.min(axis=0)  # Mínimo de cada columna de b

array([-3, -5, -9, -3])

In [46]:
b.max(axis=1)  # Máximo de cada fila de b

array([1, 5, 9])

## Pandas

El núcleo del paquete Pandas lo conforman dos tipos de objetos:

- El objeto `Series` implementa un _array_ unidimensional en el que cada elemento tiene asignado un nombre.
- El objeto `DataFrame` implementa una tabla bidimensional en el que cada fila y cada columna tienen asignado un nombre.

Para una mayor legibilidad del código, a la hora de importar el paquete Pandas se suele adoptar el convenio de asociarle el nombre `pd`.

In [47]:
import pandas as pd

### Creación de _Series_

Para crear una instancia de `Series` basta proporcionar la secuencia de elementos y usar el argumento `index` para proporcionar los nombres de esos elementos.

In [48]:
notas_examen = pd.Series([5.9, 7.6, 0.5, 9.4], index=['Ana', 'Blanca', 'Carlos', 'David'])
notas_examen

Ana       5.9
Blanca    7.6
Carlos    0.5
David     9.4
dtype: float64

Aunque es más habitual crear la instancia a partir de un diccionario.

In [49]:
notas_examen = pd.Series({'Ana': 5.9, 'Blanca': 7.6, 'Carlos': 0.5, 'David': 9.4})
notas_examen

Ana       5.9
Blanca    7.6
Carlos    0.5
David     9.4
dtype: float64

Si no se proporcionan los nombres, entonces los elementos se numeran consecutivamente a partir de 0.

In [50]:
pd.Series([5.9, 7.6, 0.5, 9.4])

0    5.9
1    7.6
2    0.5
3    9.4
dtype: float64

Las instancias de `Series` son, en esencia, _arrays_ de Numpy y, en consecuencia, todos sus elementos deben ser del mismo tipo.

In [51]:
print(f'Número de ejes: {notas_examen.ndim}')
print(f'Forma: {notas_examen.shape}')
print(f'Tamaño: {notas_examen.size}')
print(f'Tipo: {notas_examen.dtype}')

Número de ejes: 1
Forma: (4,)
Tamaño: 4
Tipo: float64

### Selección y modificación de elementos de _Series_

La selección y modificación de elementos de una instancia de `Series` se realiza habitualmente por su nombre. Para seleccionar los elementos por su índice se recomienda el uso del método `iloc`.

In [52]:
notas_examen.iloc[2]  # La tercera nota

np.float64(0.5)

In [53]:
notas_examen['Carlos']  # La nota de Carlos

np.float64(0.5)

In [54]:
notas_examen[:3]  # Las tres primeras notas

Ana       5.9
Blanca    7.6
Carlos    0.5
dtype: float64

In [55]:
notas_examen[notas_examen >= 5]  # Las notas mayores o iguales a 5

Ana       5.9
Blanca    7.6
David     9.4
dtype: float64

In [56]:
notas_examen.iloc[[3, 0]]  # La última y la primera nota

David    9.4
Ana      5.9
dtype: float64

In [57]:
notas_examen[['David', 'Ana']]  # O, equivalentemente, las notas de David y Ana

David    9.4
Ana      5.9
dtype: float64

In [58]:
notas_examen['Carlos'] = 3  # Se revisa la nota de Carlos
notas_examen

Ana       5.9
Blanca    7.6
Carlos    3.0
David     9.4
dtype: float64

Se pueden usar también rebanadas (_slices_) de nombre, pero hay que tener en cuenta que, en ese caso, el extremo derecho está incluido.

In [59]:
notas_examen['Ana':'Carlos']  # Las notas desde Ana hasta Carlos, ambos inclusive

Ana       5.9
Blanca    7.6
Carlos    3.0
dtype: float64

### Operaciones con _Series_

Como _arrays_ de Numpy que son, una función universal aplicada a una instancia de `Series` se aplica cada uno de sus elementos.

In [60]:
2 * notas_examen

Ana       11.8
Blanca    15.2
Carlos     6.0
David     18.8
dtype: float64

Al operar con varias instancias, estas se alinean por nombre.

In [61]:
notas_otro_examen = pd.Series({'David': 8.9, 'Ana': 6.4, 'Carlos': 0.9, 'Blanca': 5.7})
notas_otro_examen

David     8.9
Ana       6.4
Carlos    0.9
Blanca    5.7
dtype: float64

In [62]:
notas_examen + notas_otro_examen

Ana       12.3
Blanca    13.3
Carlos     3.9
David     18.3
dtype: float64

### Creación de _DataFrames_

Para crear una instancia de `DataFrame` basta proporcionar los elementos en una estructura bidimensional y usar los argumentos `index` y `columns` para proporcionar los nombres de las filas y las columnas, respectivamente.

In [63]:
notas = pd.DataFrame([['FEX8601', False, 5.9, 6.4],
                      ['RQI5072', False, 7.6, 5.7],
                      ['ICA5467', True,  3.0, 0.9],
                      ['SRF5964', False, 9.4, 8.9]],
                     index=['Ana', 'Blanca', 'Carlos', 'David'],
                     columns=['UVUS', 'Repetidor?', 'Examen 1', 'Examen 2'])
notas

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7
Carlos  ICA5467        True       3.0       0.9
David   SRF5964       False       9.4       8.9

Aunque es más habitual crear la instancia a partir de un diccionario de las columnas.

In [64]:
notas = pd.DataFrame({'UVUS': ['FEX8601', 'RQI5072', 'ICA5467', 'SRF5964'],
                      'Repetidor?': [False, False, True, False],
                      'Examen 1': [5.9, 7.6, 3.0, 9.4],
                      'Examen 2': [6.4, 5.7, 0.9, 8.9]},
                     index=['Ana', 'Blanca', 'Carlos', 'David'])
notas

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7
Carlos  ICA5467        True       3.0       0.9
David   SRF5964       False       9.4       8.9

Si no se proporcionan los nombres de las filas y/o de las columnas, entonces se numeran consecutivamente a partir de 0.

In [65]:
notas = pd.DataFrame([['FEX8601', False, 5.9, 6.4],
                      ['RQI5072', False, 7.6, 5.7],
                      ['ICA5467', True,  3.0, 0.9],
                      ['SRF5964', False, 9.4, 8.9]])
notas

         0      1    2    3
0  FEX8601  False  5.9  6.4
1  RQI5072  False  7.6  5.7
2  ICA5467   True  3.0  0.9
3  SRF5964  False  9.4  8.9

Aunque, si es posible, se usarán los nombres de los datos proporcionados.

In [66]:
notas = pd.DataFrame({'UVUS': ['FEX8601', 'RQI5072', 'ICA5467', 'SRF5964'],
                      'Repetidor?': [False, False, True, False],
                      'Examen 1': notas_examen,
                      'Examen 2': notas_otro_examen})
notas

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7
Carlos  ICA5467        True       3.0       0.9
David   SRF5964       False       9.4       8.9

Una instancia de `DataFrame` es, en esencia, un diccionario (ordenado) de sus columnas, donde cada una de estas es una instancia de `Series`. En consecuencia, todos los elementos de una columna deben ser del mismo tipo, pero este puede diferir entre las distintas columnas.

In [67]:
print(f'Número de ejes: {notas.ndim}')
print(f'Forma: {notas.shape}')
print(f'Tamaño: {notas.size}')
print(f'Tipo:\n{notas.dtypes}')

Número de ejes: 2
Forma: (4, 4)
Tamaño: 16
Tipo:
UVUS           object
Repetidor?       bool
Examen 1      float64
Examen 2      float64
dtype: object

### Selección y modificación de elementos de _DataFrames_

Usando el operador `[]`, las cadenas seleccionan columnas por su nombre y las rebanadas (_slices_) filas por su posición.

In [68]:
notas['UVUS']  # Al seleccionar un único nombre el resultado es una Series

Ana       FEX8601
Blanca    RQI5072
Carlos    ICA5467
David     SRF5964
Name: UVUS, dtype: object

In [69]:
notas[['Examen 1', 'Examen 2', 'Repetidor?']]  # Al seleccionar una secuencia de nombres el resultado es un DataFrame

        Examen 1  Examen 2  Repetidor?
Ana          5.9       6.4       False
Blanca       7.6       5.7       False
Carlos       3.0       0.9        True
David        9.4       8.9       False

In [70]:
notas[1:3]  # Al seleccionar filas el resultado siempre es un DataFrame

           UVUS  Repetidor?  Examen 1  Examen 2
Blanca  RQI5072       False       7.6       5.7
Carlos  ICA5467        True       3.0       0.9

No obstante lo anterior, en general es preferible usar los métodos optimizados de selección implementados en Pandas: `iat` e `iloc` para seleccionar por posición; `at` y `loc` para seleccionar por nombre.

In [71]:
notas.iat[1, 2]  # iat es el método más eficiente para obtener un único valor por su posición

np.float64(7.6)

In [72]:
notas.iloc[1, 2]  # Es equivalente a la expresión anterior, pero menos eficiente

np.float64(7.6)

In [73]:
notas.iloc[[0, 1, 2], [2, 3]]  # Se pueden seleccionar más de una fila y más de una columna por sus índices

        Examen 1  Examen 2
Ana          5.9       6.4
Blanca       7.6       5.7
Carlos       3.0       0.9

In [74]:
notas.iloc[:3, 2:4]  # Se pueden usar rebanadas de índices

        Examen 1  Examen 2
Ana          5.9       6.4
Blanca       7.6       5.7
Carlos       3.0       0.9

In [75]:
notas.iloc[1]  # Un único índice proporciona la fila correspondiente como Series

UVUS          RQI5072
Repetidor?      False
Examen 1          7.6
Examen 2          5.7
Name: Blanca, dtype: object

In [76]:
notas.iloc[:2]  # Una secuencia de índices proporciona las filas correspondientes como DataFrame

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7

In [77]:
notas.at['Blanca', 'Examen 1']  # at es el método más eficiente para obtener un único valor por su nombre

np.float64(7.6)

In [78]:
notas.loc['Blanca', 'Examen 1']  # Es equivalente a la expresión anterior, pero menos eficiente

np.float64(7.6)

In [79]:
notas.loc[['Ana', 'Blanca', 'Carlos'], ['Examen 1', 'Examen 2']]  # Se pueden seleccionar más de una fila y más de una columna por sus nombres

        Examen 1  Examen 2
Ana          5.9       6.4
Blanca       7.6       5.7
Carlos       3.0       0.9

In [80]:
notas.loc['Ana':'Carlos', 'Examen 1':'Examen 2']  # Se pueden usar rebanadas de nombres

        Examen 1  Examen 2
Ana          5.9       6.4
Blanca       7.6       5.7
Carlos       3.0       0.9

In [81]:
notas.loc['Blanca']  # Un único nombre proporciona la fila correspondiente como Series

UVUS          RQI5072
Repetidor?      False
Examen 1          7.6
Examen 2          5.7
Name: Blanca, dtype: object

In [82]:
notas.loc['Ana':'Blanca']  # Una secuencia de nombres proporciona las filas correspondientes como DataFrame

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7

Combinando selección con el operador de asignación se pueden modificar los elementos de un DataFrame.

In [83]:
notas.loc['Carlos', 'Examen 2'] = 2.8
notas

           UVUS  Repetidor?  Examen 1  Examen 2
Ana     FEX8601       False       5.9       6.4
Blanca  RQI5072       False       7.6       5.7
Carlos  ICA5467        True       3.0       2.8
David   SRF5964       False       9.4       8.9

Es incluso posible extender un DataFrame con nuevas filas y columnas.

In [84]:
notas.loc['Elena'] = ['SLE3920', 'True', 6.0, 4.8]
notas

           UVUS Repetidor?  Examen 1  Examen 2
Ana     FEX8601      False       5.9       6.4
Blanca  RQI5072      False       7.6       5.7
Carlos  ICA5467       True       3.0       2.8
David   SRF5964      False       9.4       8.9
Elena   SLE3920       True       6.0       4.8

In [85]:
notas.loc[:, 'Examen 3'] = [6.2, 8.0, None, 9.5, 6.9]  # El valor None usado para indicar un examen no realizado se guarda como un objeto NaN (Not a Number),
                                                       # que representa un número no conocido
notas

           UVUS Repetidor?  Examen 1  Examen 2  Examen 3
Ana     FEX8601      False       5.9       6.4       6.2
Blanca  RQI5072      False       7.6       5.7       8.0
Carlos  ICA5467       True       3.0       2.8       NaN
David   SRF5964      False       9.4       8.9       9.5
Elena   SLE3920       True       6.0       4.8       6.9

### Estadística descriptiva

Pandas proporciona una gran cantidad de [métodos para calcular estadísticos descriptivos](https://pandas.pydata.org/docs/reference/frame.html#computations-descriptive-stats) sobre una _Series_ o _DataFrame_. La mayoría de estos métodos, como por ejemplo `sum` (suma) y `mean` (media), calculan valores agregados que devuelven en un **nuevo** objeto de menor dimensión que el de partida. Sin embargo, algunos de ellos, como por ejemplo `cumsum` (sumas acumuladas) y `cumprod` (productos acumulados), proporcionan los resultados en un **nuevo** objeto de la misma dimensión que el de partida.

In [86]:
notas.loc[:, 'Examen 1':'Examen 3'].sum()  # Suma de las notas de cada examen

Examen 1    31.9
Examen 2    28.6
Examen 3    30.6
dtype: float64

In [87]:
notas.loc[:, 'Examen 1':'Examen 3'].cumsum()  # Sumas acumuladas de las notas de cada examen

        Examen 1  Examen 2  Examen 3
Ana          5.9       6.4       6.2
Blanca      13.5      12.1      14.2
Carlos      16.5      14.9       NaN
David       25.9      23.8      23.7
Elena       31.9      28.6      30.6

En general, estos métodos disponen de un argumento `axis` para indicar a lo largo de qué eje realizar la operación que corresponda. Si el valor de `axis` es 0 (el valor por defecto), la operación se realiza a lo largo de las filas, mientras que si el valor de `axis` es 1, la operación se realiza a lo largo de las columnas.

In [88]:
notas.loc[:, 'Examen 1':'Examen 3'].mean(axis=1)  # Media de las notas de cada alumno

Ana       6.166667
Blanca    7.100000
Carlos    2.900000
David     9.266667
Elena     5.900000
dtype: float64

Todos los métodos disponen de un argumento `skipna` para indicar qué tratamiento se les da a los valores no conocidos. Si el valor de `skipna` es `True` (valor por defecto), entonces no se incluyen en los cálculos, mientras que sí se incluyen si su valor es `False`.

In [89]:
notas.loc[:, 'Examen 1':'Examen 3'].mean(axis=1, skipna=False)  # Media de las notas de cada alumno (incluyendo los exámenes sin nota)

Ana       6.166667
Blanca    7.100000
Carlos         NaN
David     9.266667
Elena     5.900000
dtype: float64

Una opción mejor es realizar lo que se conoce como una imputación de valores. Por ejemplo, para el cálculo de la media de las notas de cada alumno tiene más sentido considerar los valores desconocidos como 0, en lugar de ignorarlos.

In [90]:
notas.loc[:, 'Examen 1':'Examen 3'].fillna(0).mean(axis=1)  # El método fillna sustituye los valores desconocidos por el valor especificado

Ana       6.166667
Blanca    7.100000
Carlos    1.933333
David     9.266667
Elena     5.900000
dtype: float64

### Lectura y escritura de ficheros de datos

Pandas implementa una serie de [funciones y métodos para la lectura y escritura de ficheros de datos](https://pandas.pydata.org/docs/user_guide/io.html) en distintos formatos.

Un caso habitual es el de disponer de un conjunto de datos guardado en un fichero con [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) (_comma separated values_). Para leer los datos del fichero en un _DataFrame_ se proporciona la función `read_csv`, mientras que para escribir los datos de un _DataFrame_ en el fichero se proporciona el método `to_csv`. Ambas funciones disponen de argumentos que permiten adaptar la lectura y escritura al formato concreto del fichero.

In [91]:
notas = pd.read_csv('notas.csv',         # Ruta del fichero a leer
                    skiprows=3,          # Descartar las tres primeras líneas del fichero
                    index_col='Alumno',  # La columna Alumno contiene el nombre de las filas
                    na_values=-1)        # Tratar el -1 como valor no conocido

In [92]:
notas.head()  # Primeras filas del DataFrame

        Repetidor?  Examen 1  Examen 2  Examen 3
Alumno
Ana          False       5.9       6.4       6.2
Blanca       False       7.6       5.7       8.0
Carlos        True       3.0       2.8       NaN
David        False       9.4       8.9       9.5
Elena         True       6.0       4.8       6.9

In [93]:
notas.tail()  # Últimas filas del DataFrame

          Repetidor?  Examen 1  Examen 2  Examen 3
Alumno
Silvia          True       9.3       5.2       NaN
Tomás           True       4.0       4.0       2.5
Ulises          True       2.1       8.3       9.7
Víctor          True       0.6       9.2       5.1
Zacarías        True       0.1       6.4       7.2

In [94]:
notas.loc[:, 'Nota final'] = notas.loc[:, 'Examen 1':'Examen 3'].fillna(0).mean(axis=1)  # Calculamos la nota final de cada alumno como la media de las notas de los exámenes
notas

           Repetidor?  Examen 1  Examen 2  Examen 3  Nota final
Alumno
Ana             False       5.9       6.4       6.2    6.166667
Blanca          False       7.6       5.7       8.0    7.100000
Carlos           True       3.0       2.8       NaN    1.933333
David           False       9.4       8.9       9.5    9.266667
Elena            True       6.0       4.8       6.9    5.900000
Felipe           True       7.2       NaN       2.1    3.100000
Guillermo       False       NaN       8.5       6.3    4.933333
Héctor          False       4.1       4.6       0.6    3.100000
Inés            False       2.7       NaN       5.6    2.766667
Julia           False       7.2       7.0       NaN    4.733333
Lucía           False       7.1       9.0       8.0    8.033333
Miguel           True       0.4       NaN       7.7    2.700000
Noelia          False       9.4       NaN       4.9    4.766667
Òscar            True       6.1       5.9       8.2    6.733333
Pablo            True       6.8       2.2       9.1    6.033333
Rocío           False       NaN       8.0       9.9    5.966667
Silvia           True       9.3       5.2       NaN    4.833333
Tomás            True       4.0       4.0       2.5    3.500000
Ulises           True       2.1       8.3       9.7    6.700000
Víctor           True       0.6       9.2       5.1    4.966667
Zacarías         True       0.1       6.4       7.2    4.566667

In [95]:
notas = notas.round({'Nota final': 1})  # Redondeamos la nota final a un decimal
notas

           Repetidor?  Examen 1  Examen 2  Examen 3  Nota final
Alumno
Ana             False       5.9       6.4       6.2         6.2
Blanca          False       7.6       5.7       8.0         7.1
Carlos           True       3.0       2.8       NaN         1.9
David           False       9.4       8.9       9.5         9.3
Elena            True       6.0       4.8       6.9         5.9
Felipe           True       7.2       NaN       2.1         3.1
Guillermo       False       NaN       8.5       6.3         4.9
Héctor          False       4.1       4.6       0.6         3.1
Inés            False       2.7       NaN       5.6         2.8
Julia           False       7.2       7.0       NaN         4.7
Lucía           False       7.1       9.0       8.0         8.0
Miguel           True       0.4       NaN       7.7         2.7
Noelia          False       9.4       NaN       4.9         4.8
Òscar            True       6.1       5.9       8.2         6.7
Pablo            True       6.8       2.2       9.1         6.0
Rocío           False       NaN       8.0       9.9         6.0
Silvia           True       9.3       5.2       NaN         4.8
Tomás            True       4.0       4.0       2.5         3.5
Ulises           True       2.1       8.3       9.7         6.7
Víctor           True       0.6       9.2       5.1         5.0
Zacarías         True       0.1       6.4       7.2         4.6

In [96]:
notas.to_csv('notas_finales.csv',  # Ruta del fichero a escribir
             na_rep = '-1')        # Escribir los valores no conocidos como -1